{"name":"Local: try_exception","url":"/Users/nazmulhossain/Document/Phitron/Semester_3/SDT/OOP and Python Programming/Week_1/Module_3/try_exception.py","tests":[{"id":1744215037272,"input":"","output":""}],"interactive":false,"memoryLimit":1024,"timeLimit":3000,"srcPath":"/Users/nazmulhossain/Document/Phitron/Semester_3/SDT/OOP and Python Programming/Week_1/Module_3/try_exception.py","group":"local","local":true}